using UnityEngine;
using UnityEngine.InputSystem;

namespace BrawlShooter.Core
{
    /// <summary>
    /// Lightweight runtime replacement for the generated InputAction wrapper so the sample compiles out of the box.
    /// Replace this with the real C# class generated by the Input System.
    /// </summary>
    public sealed class PlayerInputActions : IInputActionCollection
    {
        public GameplayActions Gameplay { get; }

        public PlayerInputActions()
        {
            var asset = ScriptableObject.CreateInstance<InputActionAsset>();
            var gameplayMap = new InputActionMap("Gameplay");
            asset.AddActionMap(gameplayMap);

            var move = gameplayMap.AddAction("Move", InputActionType.Value, binding: "<Gamepad>/leftStick");
            move.AddCompositeBinding("2DVector")
                .With("Up", "<Keyboard>/w")
                .With("Down", "<Keyboard>/s")
                .With("Left", "<Keyboard>/a")
                .With("Right", "<Keyboard>/d");

            var aim = gameplayMap.AddAction("Aim", InputActionType.Value, "<Pointer>/delta");
            var fire = gameplayMap.AddAction("Fire", InputActionType.Button, "<Mouse>/leftButton");
            var super = gameplayMap.AddAction("Super", InputActionType.Button, "<Mouse>/rightButton");
            var dash = gameplayMap.AddAction("Dash", InputActionType.Button, "<Keyboard>/space");

            Gameplay = new GameplayActions(gameplayMap, move, aim, fire, super, dash);
            Asset = asset;
        }

        public InputActionAsset Asset { get; }

        public void Enable() => Asset.Enable();
        public void Disable() => Asset.Disable();

        public void Dispose()
        {
            Object.Destroy(Asset);
        }

        public struct GameplayActions
        {
            private readonly InputActionMap _map;

            public GameplayActions(InputActionMap map, InputAction move, InputAction aim, InputAction fire, InputAction super, InputAction dash)
            {
                _map = map;
                Move = move;
                Aim = aim;
                Fire = fire;
                Super = super;
                Dash = dash;
            }

            public InputAction Move { get; }
            public InputAction Aim { get; }
            public InputAction Fire { get; }
            public InputAction Super { get; }
            public InputAction Dash { get; }
        }
    }
}
